### PR TITLE
fix build warnings (-Wmaybe-uninitialized)

### PR DESCRIPTION
**Pull request by remicollet**
Remaining warnings are [-Wdeprecated-declarations]

### CODE REVIEW

**Comment by Danack** [comment]
Oh....darn.

Just looking at the PR highlights a really obvious using null pointer bug....that exists through all of the ImagickKernel stuff. e.g.

```
$kernel1 = new ImagickKernel();
$kernel1->addUnityKernel(1.0);
```
gives a segfault....

I'll need to find an afternoon to look at it all properly.

**Comment by Danack** [comment]
Hi @remicollet - i fixed the horrendous bug for the null pointer errors, and as part of that I think this PR is no longer required. Please could you confirm?

Also, I would like to enable -Wmaybe-uninitialized as part of the strict CFLAGs that Imagick is tested with. Do you have any insights as to why it would sometimes fail? https://travis-ci.org/Danack/imagick/builds/138573279


cheers
Dan

**Comment by remicollet** [comment]
> Please could you confirm?

```
I still have the same warning with recent gcc:

/work/GIT/imagick/imagickkernel_class.c: In function 'zim_imagickkernel_addkernel':
/work/GIT/imagick/imagickkernel_class.c:650:27: warning: 'kernel_info_target' may be used uninitialized in this function [-Wmaybe-uninitialized]
  kernel_info_target->next = kernel_info_add_clone;
                           ^
/work/GIT/imagick/imagickkernel_class.c:627:14: note: 'kernel_info_target' was declared here
  KernelInfo *kernel_info_target;
              ^
```

> Do you have any insights as to why it would sometimes fail?

Perhaps a old gcc version with no support for this option (it fails at config time, so probably during the gcc check).

**Comment by dlemstra** [comment]
I think you are still getting this warning because the compiler cannot deduct that internp->kernel_info (https://github.com/mkoppanen/imagick/blob/master/imagickkernel_class.c#L644) cannot be null. At least that is what your code is assuming now, not sure if that is correct though. You might want to take another look at the code.

**Comment by remicollet** [comment]
I think you are still getting this warning because the compiler cannot deduct ...

As is cannot be NULL, using do { } while should be a bit faster (save one test, really small opt), but save the compiler warning ;)

**Pull request merged**
