### PR TITLE
TLS issue with progress callback

### PR DESCRIPTION
**Pull request by jbboehr**
#42 https://github.com/mkoppanen/imagick/issues/42#issuecomment-125779929

### CODE REVIEW

**Comment by Danack** [comment]
Thanks - can you say under what circumstances this caused an issue, so that I can check that that issue isn't anywhere else?

**Comment by jbboehr** [comment]
@Danack My understanding of PHP internals isn't particularly comprehensive, and I know very little about pthreads, but based on my tests on Ubuntu 14.04, the callback function is executed from several (about 8) different threads, only one of which is the original thread with the PHP interpreter. In PHP7, they started using thread local storage for ZTS, so EG(function_table) is only accessible from the original thread. Each thread has a different instance of zend_executor_globals; the thread started by imagemagick doesn't have an initialized one. Originally, I tried to set the TSRM context in the different thread, but I couldn't get that working for some reason. I suppose the ideal case would be that imagemagick only executes the callback in the original thread, which is essentially what this patch does, at least in the case of the user-defined callback function.

**Comment by jbboehr** [comment]
Related to the failing tests: is the imagemagick SVN no longer available?

**Comment by jbboehr** [comment]
I was going to try to fix the failing tests, but then TravisCI's PHP7 started having some weird error: https://travis-ci.org/jbboehr/imagick/jobs/73119519

**Comment by jbboehr** [comment]
I merged master into and fixed the failing tests in this branch: https://github.com/mkoppanen/imagick/compare/phpseven...jbboehr:phpseven

**Comment by Danack** [comment]
Sorry for taking so long to look at this. 

Can you tell me under what circumstances the problem occurs that this patch is going to solve? I want to be able to write a test to make sure that the problem is actually solved.

I don't think just returning true is going to be acceptable.....if the callback function can't be relied on, it would be better to not allow it to be setup, rather than having it just be flaky, as there is no guarantee that the original thread would ever trigger it.

**Comment by jbboehr** [comment]
This patch simply prevents the segmentation fault in PHP7 in tests/127_Imagick_progressMonitor_basic.phpt:
https://travis-ci.org/mkoppanen/imagick/jobs/66430334#L3832

The circumstances would be when the progress callback is invoked in a different thread in PHP7. I'm not very familiar with threading or the imagemagick internals, but the ideal case would be to only trigger the callback in the original thread.

In PHP5, it was possible to invoke the same interpreter instance in different threads, which is why this does not segfault on PHP5, however I could not get this to work in PHP7 due to the usage of thread local storage.

**Comment by jbboehr** [comment]
I think at the very least, we want to avoid a segfault, but as you say, another option would be to disable the feature in PHP7, if a better solution can't be found.

**Comment by Danack** [comment]
Okay merged.

I think this is going to have to be a documented limitation. The callback stuff will work to some extent, so disabling it completely wouldn't be great, but I'm not sure how reliably it would work with multiple threads.

Though tbh, the OpenMP stuff doesn't work that reliably _anyway_ and I recommend disabling it...so yeah, something to 'fix' via documenting it.

**Pull request merged**
