### PR TITLE
Proposed fix for Issue #187

### PR DESCRIPTION
**Pull request by nacc**
So, this does pass the testing for 6.9.6-6. But it regresses the 7.x ImageMagick tests, so is not suitable for merging (yet). I'm actually not sure how 7.x passes given that the same change was made to that code that regressed 6.x test. So perhaps there is another moving part. I also am not sure this is at all the right solution, but just wanted to get the patch(es) out there for discussion.

### CODE REVIEW

**Comment by Danack** [comment]
The underlying issue is being fixed in ImageMagick.

**Comment by nacc** [comment]
Do you have a reference to an upstream bug or discussion?

Thanks!
-Nish

**Comment by Danack** [comment]
Here - https://github.com/ImageMagick/ImageMagick/issues/316

I was going to test against it tomorrow.

**Comment by nacc** [comment]
Thank you!

**Pull request closed without merging**
